# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inference_service_pb2 as inference__service__pb2


class InfererStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.infer = channel.stream_unary(
        '/inferer.Inferer/infer',
        request_serializer=inference__service__pb2.Request.SerializeToString,
        response_deserializer=inference__service__pb2.Reply.FromString,
        )


class InfererServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def infer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InfererServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'infer': grpc.stream_unary_rpc_method_handler(
          servicer.infer,
          request_deserializer=inference__service__pb2.Request.FromString,
          response_serializer=inference__service__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inferer.Inferer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
